package pe.gob.onpe.sceorcbackend.model.dto.reporte;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class ComparacionDigitacionAutomaticaDto {
    private String codigoAmbitoElectoral;
    private String nombreAmbitoElectoral;
    private String codigoCentroComputo;
    private String nombreCentroComputo;
    private String codigoUbigeo;
    private String departamento;
    private String provincia;
    private String distrito;
    private String mesa;
    private String numeroCopia;
    private String digitoChequeoEscrutinio;
    private Integer posicion;
    private String descripcion;
    private String votoCiudadanoAutom;
    private String votoCiudadanoManual;
    private String firmaAutom;
    private String firmaManual;
    private String votoAutomTotal;
    private String votoManualTotal;
    private String votoAutom1;
    private String votoManual1;
    private String votoAutom2;
    private String votoManual2;
    private String votoAutom3;
    private String votoManual3;
    private String votoAutom4;
    private String votoManual4;
    private String votoAutom5;
    private String votoManual5;
    private String votoAutom6;
    private String votoManual6;
    private String votoAutom7;
    private String votoManual7;
    private String votoAutom8;
    private String votoManual8;
    private String votoAutom9;
    private String votoManual9;
    private String votoAutom10;
    private String votoManual10;
    private String votoAutom11;
    private String votoManual11;
    private String votoAutom12;
    private String votoManual12;
    private String votoAutom13;
    private String votoManual13;
    private String votoAutom14;
    private String votoManual14;
    private String votoAutom15;
    private String votoManual15;
    private String votoAutom16;
    private String votoManual16;
    private String votoAutom17;
    private String votoManual17;
    private String votoAutom18;
    private String votoManual18;
    private String votoAutom19;
    private String votoManual19;
    private String votoAutom20;
    private String votoManual20;
    private String votoAutom21;
    private String votoManual21;
    private String votoAutom22;
    private String votoManual22;
    private String votoAutom23;
    private String votoManual23;
    private String votoAutom24;
    private String votoManual24;
    private String votoAutom25;
    private String votoManual25;
    private String votoAutom26;
    private String votoManual26;
    private String votoAutom27;
    private String votoManual27;
    private String votoAutom28;
    private String votoManual28;
    private String votoAutom29;
    private String votoManual29;
    private String votoAutom30;
    private String votoManual30;
    private String votoAutom31;
    private String votoManual31;
    private String votoAutom32;
    private String votoManual32;
    private String dif1;
    private String dif2;
    private String dif3;
    private String dif4;
    private String dif5;
    private String dif6;
    private String dif7;
    private String dif8;
    private String dif9;
    private String dif10;
    private String dif11;
    private String dif12;
    private String dif13;
    private String dif14;
    private String dif15;
    private String dif16;
    private String dif17;
    private String dif18;
    private String dif19;
    private String dif20;
    private String dif21;
    private String dif22;
    private String dif23;
    private String dif24;
    private String dif25;
    private String dif26;
    private String dif27;
    private String dif28;
    private String dif29;
    private String dif30;
    private String dif31;
    private String dif32;
    private String difTotal;
    private String validacionVoto;

    public void calcularDiferencias() {
        this.dif1 = comparar(votoAutom1, votoManual1);
        this.dif2 = comparar(votoAutom2, votoManual2);
        this.dif3 = comparar(votoAutom3, votoManual3);
        this.dif4 = comparar(votoAutom4, votoManual4);
        this.dif5 = comparar(votoAutom5, votoManual5);
        this.dif6 = comparar(votoAutom6, votoManual6);
        this.dif7 = comparar(votoAutom7, votoManual7);
        this.dif8 = comparar(votoAutom8, votoManual8);
        this.dif9 = comparar(votoAutom9, votoManual9);
        this.dif10 = comparar(votoAutom10, votoManual10);
        this.dif11 = comparar(votoAutom11, votoManual11);
        this.dif12 = comparar(votoAutom12, votoManual12);
        this.dif13 = comparar(votoAutom13, votoManual13);
        this.dif14 = comparar(votoAutom14, votoManual14);
        this.dif15 = comparar(votoAutom15, votoManual15);
        this.dif16 = comparar(votoAutom16, votoManual16);
        this.dif17 = comparar(votoAutom17, votoManual17);
        this.dif18 = comparar(votoAutom18, votoManual18);
        this.dif19 = comparar(votoAutom19, votoManual19);
        this.dif20 = comparar(votoAutom20, votoManual20);
        this.dif21 = comparar(votoAutom21, votoManual21);
        this.dif22 = comparar(votoAutom22, votoManual22);
        this.dif23 = comparar(votoAutom23, votoManual23);
        this.dif24 = comparar(votoAutom24, votoManual24);
        this.dif25 = comparar(votoAutom25, votoManual25);
        this.dif26 = comparar(votoAutom26, votoManual26);
        this.dif27 = comparar(votoAutom27, votoManual27);
        this.dif28 = comparar(votoAutom28, votoManual28);
        this.dif29 = comparar(votoAutom29, votoManual29);
        this.dif30 = comparar(votoAutom30, votoManual30);
        this.dif31 = comparar(votoAutom31, votoManual31);
        this.dif32 = comparar(votoAutom32, votoManual32);
        this.difTotal = comparar(votoAutomTotal, votoManualTotal);
    }

    private String comparar(String a, String m) {
        if (a == null || m == null) return "NO";
        return !a.equals(m) ? "SI" : "NO";
    }
}
