sonar.projectKey=sce_orc_backend
sonar.projectName=sce_orc_backend
sonar.projectVersion=1.0

sonar.sources=src/main

sonar.java.binaries=target/classes
sonar.exclusions=src/main/resources/application.properties
sonar.inclusions=**/*.java
sonar.sourceEncoding=UTF-8

# Opcional: configuración del servidor SonarQube
sonar.host.url=http://10.220.80.60:9000/
sonar.login=squ_23d5b03f3ebe763e3c8a9fa27d1218bfe04c9ee3
