server.port=8080
server.servlet.context-path=${APPLICATION_ROOT}

logging.level.root=INFO
logging.level.pe.gob.onpe.scebackend.task=INFO

spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.default_schema=${DB_DEFAULT_SCHEMA}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=WARN
spring.jpa.properties.hibernate.type.descriptor.sql.BasicBinder.log.level=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN

fileserver.path=${FILE_SERVER_PATH}
fileserver.files=${FILE_SERVER_FILES}
sce.schema.default=sce_nacion

#Rabbit configuration
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=0

sasa.url = ${SASA_URL}
sasa.codigo = SCE

spring.enable.scheduling = true

coordenada.url = ${COORDENADA_URL}

security.jwt.tokenExpirationTime=60
security.jwt.refreshTokenExpTime=70
security.jwt.tokenIssuer=ONPE
security.jwt.tokenSigningKey=${JWT_SECRET}


####################INICIO PROPERTIES DE KAFKA##################

# Configuracion del broker de Kafka
spring.kafka.bootstrap-servers=${SERVER_PORT_KAFKA}

# Configuracion del productor
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Configuracion del consumidor
spring.kafka.consumer.group-id=grupo-nacion
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest


kafka.topic.request=topico-solicitudes

spring.kafka.consumer.properties.spring.json.value.default.type=pe.gob.onpe.scebackend.model.dto.transmision.TransmisionNacionRequestDto
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.producer.properties.spring.json.add.type.headers=false



# Desactivar logs de Kafka
logging.level.org.apache.kafka=OFF
logging.level.kafka=OFF
logging.level.org.springframework.kafka=OFF

####################FIN PROPERTIES DE KAFKA##################


#################### INICIO PUESTA CERO PR #######################

sce.pr-admin.url=${PR_ADMIN_URL}
sce.pr-admin.pc.token=${PR_ADMIN_TOKEN}
cron.expression.puesta-cero-pr=0 0/1 * * * ?

#################### FIN PUESTA CERO PR ###########################

#######INICIO PROPERTIES PARA RESPALDO DE BASE DATOS##############
util.respaldo.path=/usr/bin/

sce.cc.connect-timeout=300000
sce.cc.url-ping=${CONTEXTO_ORC}/parametro-conexion-cc/ping


auth.client.id=sce-middleware
auth.client.secret=${CLIENT_SECRET}
sce.cc.url-extranjero-acta=${CONTEXTO_ORC}/extranjero/uploadActaDigitization
sce.cc.url-jne-recepcion=${CONTEXTO_ORC}/jneRecepcion/resolucionOficio

security.rsa.public-key=${RSA_PUBLIC_KEY}
security.rsa.private-key=${RSA_PRIVATE_KEY}

# ============================================
# CONFIGURACION DEL POOL HIKARICP
# ============================================

spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL_SIZE:8}
spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE:2}
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000



# ============================================
# DATASOURCE (Puesta a Cero)
# ============================================
maintenance.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
maintenance.datasource.username=${DB_USER}
maintenance.datasource.password=${DB_PASSWORD}
maintenance.datasource.hikari.maximum-pool-size=1
maintenance.datasource.hikari.minimum-idle=1
maintenance.datasource.hikari.connection-timeout=60000
maintenance.datasource.hikari.idle-timeout=1800000
maintenance.datasource.hikari.max-lifetime=1800000
maintenance.datasource.hikari.pool-name=MaintenanceHikariPool
maintenance.datasource.hikari.connection-init-sql=SET search_path TO ${DB_DEFAULT_SCHEMA}
